### ISSUE TITLE
Moving from Harp to Docsify for markdown -> generated docs

### ISSUE THREAD

**Issue by atuttle** [atuttle/TaffyDocs#21]
I've done the initial work to switch from using Harp to generate the documentation to using [docsify](https://docsify.js.org/). It solves all of the same problems as my custom solution, generates something with basically the same structure by default, has better theming support, and more features out of the box -- so it's kind of a no-brainer to me. Even better, it can auto-deploy after each git push/merge so that's less manual work for me to do!

You can see the work-in-progress updated docs here: https://laughing-knuth-d64af0.netlify.app/

## Help Wanted!

All of the infrastructure is in place, so all that's left to do is to update the docs themselves to enable syntax highlighting on code blocks. I've [completed the changes for the most recent version of Taffy, 3.2.0](https://github.com/atuttle/TaffyDocs/commit/27ed70fc338f7c76b8f87f42577c12496a8e5e53), so you can take a look at that change to see what's required. It's really rather simple:

- Existing code blocks are prefixed with 4 spaces (markdown syntax to denote a code block)
- I want to convert them to fenced code blocks by wrapping them with 3 backticks  ` ``` `, in part because this also allows us to specify the code language for that code block. You can see in [my changes to 3.2.0.md](https://github.com/atuttle/TaffyDocs/commit/27ed70fc338f7c76b8f87f42577c12496a8e5e53) that for CFML blocks I've used the language identifier `xml`, and for CFScript blocks I've used the identifier `js`. These are the closest supported syntaxes and they actually work [pretty decently](https://laughing-knuth-d64af0.netlify.app/#/3.2.0?id=taffydefault).

If you'd like to contribute to Taffy by making the same changes to the other documentation files, pull requests are welcome!

> ⚠️ Please create your branch from the `docsify` branch, or [click here](https://github.com/atuttle/TaffyDocs/tree/docsify/src), select the file you want to update, and then click the pencil icon in the upper right to edit it directly on github.

These are the files still in need of updating
- [x] `3.1.0.md`
- [x] `3.0.2.md`
- [x] `3.0.1.md`
- [x] `3.0.0.md`
- [x] `2.2.4.md`
- [x] `2.2.3.md`
- [x] `2.2.0.md`
- [x] `2.1.0.md`
- [x] `2.0.1.md`
- [x] `2.0.0.md`

## New to pull requests? Start here!

If you're a complete PR noob and want ALL of the little details explained to you, [here's a completely free video course that walks you through all of the steps!](https://egghead.io/courses/how-to-contribute-to-an-open-source-project-on-github)

If you've made a few pull requests but need a refresher or just want a few tips, I'd recommend reading [this](https://adamtuttle.codes/blog/2014/your-first-github-pull-request/).

**Comment by euans** [comment]
+ 3.1.0.md Has been completed.

**Comment by euans** [comment]
+3.0.0.md has been completed.  3.0.1 and 3.0.2 appear to be redirected to 3.0.0.

**Comment by euans** [comment]
+ 2.2.4.md has been completed.

**Comment by euans** [comment]
+ 2.2.3 has been completed.

**Comment by euans** [comment]
2.1.0 - 2.0.0 has bee completed

**Comment by andreasRu** [comment]
My goodness!!! Just wanted to contribute, but it's already closed!!! Nice to see it done already!!! Congrats and thanks to @euans ! Just starred this repo 👍
